document.write( '<html><head>\n' );
document.write( '<meta charset=\"utf-8\">\n' );
document.write( '<title>(3) Playing a local video</title>\n' );
document.write( '<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\">\n' );
document.write( '<style>\n' );
document.write( 'html, body {\n' );
document.write( 'background: black;\n' );
document.write( 'color: white;\n' );
document.write( '}\n' );
document.write( 'html, body, video {\n' );
document.write( 'padding: 0;\n' );
document.write( 'margin: 0;\n' );
document.write( '}\n' );
document.write( 'video {\n' );
document.write( 'position: absolute;\n' );
document.write( 'top: 0;\n' );
document.write( 'left: 0;\n' );
document.write( 'bottom: 0;\n' );
document.write( 'right: 0;\n' );
document.write( 'width: 100%;\n' );
document.write( 'height: 100%;\n' );
document.write( '}\n' );
document.write( '</style>\n' );
document.write( '<style id=\"tableconvert-font-styles\">\n' );
document.write( '/* TableConvert Extension - Essential Font Definition Only */\n' );
document.write( '@font-face {\n' );
document.write( '  font-family: \"tableconvert-icon\";\n' );
document.write( '  src: url(\'https://at.alicdn.com/t/c/font_1011144_jmo4009ffif.woff2?t=1719821135173\') format(\'woff2\'),\n' );
document.write( '       url(\'https://at.alicdn.com/t/c/font_1011144_jmo4009ffif.woff?t=1719821135173\') format(\'woff\'),\n' );
document.write( '       url(\'https://at.alicdn.com/t/c/font_1011144_jmo4009ffif.ttf?t=1719821135173\') format(\'truetype\');\n' );
document.write( '  font-display: swap;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '/* Essential scrollbar styles for dropdown */\n' );
document.write( '.tableconvert-dropdown-content::-webkit-scrollbar {\n' );
document.write( '  width: 3px;\n' );
document.write( '}\n' );
document.write( '.tableconvert-dropdown-content::-webkit-scrollbar-track {\n' );
document.write( '  background: rgba(241, 245, 249, 0.4);\n' );
document.write( '  border-radius: 1.5px;\n' );
document.write( '}\n' );
document.write( '.tableconvert-dropdown-content::-webkit-scrollbar-thumb {\n' );
document.write( '  background: rgba(203, 213, 225, 0.6);\n' );
document.write( '  border-radius: 1.5px;\n' );
document.write( '}\n' );
document.write( '.tableconvert-dropdown-content::-webkit-scrollbar-thumb:hover {\n' );
document.write( '  background: rgba(148, 163, 184, 0.7);\n' );
document.write( '}\n' );
document.write( '  </style></head>\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '<video id=\"myVideo\" controls=\"\" controlslist=\"nodownload\" width=\"600\">\n' );
document.write( '  <source src=\"https://upload.wikimedia.org/wikipedia/commons/transcoded/c/c0/Big_Buck_Bunny_4K.webm/Big_Buck_Bunny_4K.webm.720p.vp9.webm\" type=\"video/mp4\">\n' );
document.write( '<track kind=\"subtitles\" label=\"English\" srclang=\"en\" default=\"\" src=\"blob:http://127.0.0.1:5500/d1069a83-8cb8-4759-b8e2-c0edeb3f7603\"></video>\n' );
document.write( '\n' );
document.write( '<!-- Check https://quuz.org/webvtt/ for validation. -->\n' );
document.write( '<script type=\"text/vtt\" id=\"subtitle\" data-label=\"English\" data-lang=\"en\">\n' );
document.write( 'WEBVTT\n' );
document.write( '\n' );
document.write( '00:00:05.489 --> 00:00:06.201\n' );
document.write( '( crow cawing )\n' );
document.write( '\n' );
document.write( '00:00:20.300 --> 00:00:22.000\n' );
document.write( '( bird chirping )\n' );
document.write( '\n' );
document.write( '00:00:24.980 --> 00:00:27.000\n' );
document.write( 'THE PEACH OPEN MOVIE PROJECT\n' );
document.write( 'PRESENTS\n' );
document.write( '\n' );
document.write( '00:00:28.000 --> 00:00:33.000\n' );
document.write( 'BIG BUCK BUNNY\n' );
document.write( '\n' );
document.write( '00:00:40.000 --> 00:00:42.000\n' );
document.write( '( snoring )\n' );
document.write( '\n' );
document.write( '00:00:54.200 --> 00:00:56.000\n' );
document.write( '( yawning )\n' );
document.write( '\n' );
document.write( '00:01:21.000 --> 00:01:24.000\n' );
document.write( '( peaceful music playing )\n' );
document.write( '\n' );
document.write( '00:01:38.800 --> 00:01:39.333\n' );
document.write( '( chomps )\n' );
document.write( '\n' );
document.write( '00:02:15.000 --> 00:02:17.000\n' );
document.write( '( footsteps running )\n' );
document.write( '\n' );
document.write( '00:02:17.000 --> 00:02:18.000\n' );
document.write( '( leaves rustling )\n' );
document.write( '\n' );
document.write( '00:02:30.985 --> 00:02:33.231\n' );
document.write( '( sneaky music playing )\n' );
document.write( '\n' );
document.write( '00:02:37.230 --> 00:02:38.111\n' );
document.write( '( squirrel chirps )\n' );
document.write( '\n' );
document.write( '00:02:45.000 --> 00:02:46.656\n' );
document.write( '( squirrels laughing )\n' );
document.write( '\n' );
document.write( '00:02:56.000 --> 00:03:00.000\n' );
document.write( '( banging )\n' );
document.write( '\n' );
document.write( '00:03:02.000 --> 00:03:05.000\n' );
document.write( '- ( action music playing )\n' );
document.write( '- ( banging continues )\n' );
document.write( '\n' );
document.write( '00:03:29.000 --> 00:03:32.000\n' );
document.write( '( sad music playing )\n' );
document.write( '\n' );
document.write( '00:03:47.980 --> 00:03:52.222\n' );
document.write( '( action music playing )\n' );
document.write( '\n' );
document.write( '00:04:18.650 --> 00:04:24.832\n' );
document.write( '( epic music playing )\n' );
document.write( '\n' );
document.write( '00:04:34.734 --> 00:04:38.000\n' );
document.write( '( joyful music playing )\n' );
document.write( '\n' );
document.write( '00:04:42.000 --> 00:04:49.000\n' );
document.write( '( epic music continues )\n' );
document.write( '\n' );
document.write( '00:05:32.000 --> 00:05:35.666\n' );
document.write( '- ( branch cracking )\n' );
document.write( '- ( squirrels chirping )\n' );
document.write( '\n' );
document.write( '00:05:41.000 --> 00:05:42.000\n' );
document.write( '( screams )\n' );
document.write( '\n' );
document.write( '00:05:49.128 --> 00:05:52.000\n' );
document.write( '- ( exclaims )\n' );
document.write( '- ( rumbling )\n' );
document.write( '\n' );
document.write( '00:06:17.000 --> 00:06:20.000\n' );
document.write( '( screams )\n' );
document.write( '\n' );
document.write( '00:07:04.000 --> 00:07:06.000\n' );
document.write( '( branches cracking )\n' );
document.write( '\n' );
document.write( '00:07:20.559 --> 00:07:22.431\n' );
document.write( '( leaves snapping )\n' );
document.write( '\n' );
document.write( '00:07:25.444 --> 00:07:26.888\n' );
document.write( '( screams )\n' );
document.write( '\n' );
document.write( '00:07:41.000 --> 00:07:42.300\n' );
document.write( '( squirrel screaming )\n' );
document.write( '\n' );
document.write( '00:07:46.500 --> 00:07:53.500\n' );
document.write( '( heroic music playing )\n' );
document.write( '\n' );
document.write( '00:08:15.500 --> 00:08:21.679\n' );
document.write( '( epic closing music playing )\n' );
document.write( '\n' );
document.write( '00:09:44.540 --> 00:09:50.540\n' );
document.write( '( epic closing music continues )\n' );
document.write( '\n' );
document.write( '00:10:18.808 --> 00:10:25.707\n' );
document.write( '- ( eagles cawing, birds chirping )\n' );
document.write( '- ( wind rustling )\n' );
document.write( '</script>\n' );
document.write( '\n' );
document.write( '<script>\n' );
document.write( 'function init() {\n' );
document.write( '// http://www.html5rocks.com/en/tutorials/track/basics/\n' );
document.write( '// https://www.iandevlin.com/blog/2015/02/javascript/dynamically-adding-text-tracks-to-html5-video\n' );
document.write( 'var video = document.querySelector(\'video\');\n' );
document.write( 'var subtitle = document.getElementById(\'subtitle\');\n' );
document.write( 'var blob = new Blob([subtitle.textContent.trimStart()], {type: \'text/vtt\'});\n' );
document.write( 'var track = document.createElement(\'track\');\n' );
document.write( 'track.kind = \'subtitles\';\n' );
document.write( 'track.label = subtitle.dataset.label;\n' );
document.write( 'track.srclang = subtitle.dataset.lang;\n' );
document.write( 'track.default = true;\n' );
document.write( 'track.src = URL.createObjectURL(blob);\n' );
document.write( 'video.appendChild(track);\n' );
document.write( '}\n' );
document.write( 'init();\n' );
document.write( 'document.addEventListener(\'DOMContentLoaded\', function() {\n' );
document.write( '  const videoElement = document.getElementById(\'myVideo\');\n' );
document.write( '  if (videoElement) {\n' );
document.write( '    videoElement.addEventListener(\'contextmenu\', function(event) {\n' );
document.write( '      // Prevents the browser\'s default context menu from appearing\n' );
document.write( '      event.preventDefault();\n' );
document.write( '    });\n' );
document.write( '  }\n' );
document.write( '});\n' );
document.write( 'const myVideo = document.getElementById(\'myVideo\');\n' );
document.write( 'myVideo.addEventListener(\'contextmenu\', (e) => {\n' );
document.write( '  e.preventDefault();\n' );
document.write( '});\n' );
document.write( '\n' );
document.write( '</script>\n' );
document.write( '\n' );
document.write( '<!-- Code injected by live-server -->\n' );
document.write( '<script>\n' );
document.write( '	// <![CDATA[  <-- For SVG support\n' );
document.write( '	if (\'WebSocket\' in window) {\n' );
document.write( '		(function () {\n' );
document.write( '			function refreshCSS() {\n' );
document.write( '				var sheets = [].slice.call(document.getElementsByTagName(\"link\"));\n' );
document.write( '				var head = document.getElementsByTagName(\"head\")[0];\n' );
document.write( '				for (var i = 0; i < sheets.length; ++i) {\n' );
document.write( '					var elem = sheets[i];\n' );
document.write( '					var parent = elem.parentElement || head;\n' );
document.write( '					parent.removeChild(elem);\n' );
document.write( '					var rel = elem.rel;\n' );
document.write( '					if (elem.href && typeof rel != \"string\" || rel.length == 0 || rel.toLowerCase() == \"stylesheet\") {\n' );
document.write( '						var url = elem.href.replace(/(&|?)_cacheOverride=d+/, \'\');\n' );
document.write( '						elem.href = url + (url.indexOf(\'?\') >= 0 ? \'&\' : \'?\') + \'_cacheOverride=\' + (new Date().valueOf());\n' );
document.write( '					}\n' );
document.write( '					parent.appendChild(elem);\n' );
document.write( '				}\n' );
document.write( '			}\n' );
document.write( '			var protocol = window.location.protocol === \'http:\' ? \'ws://\' : \'wss://\';\n' );
document.write( '			var address = protocol + window.location.host + window.location.pathname + \'/ws\';\n' );
document.write( '			var socket = new WebSocket(address);\n' );
document.write( '			socket.onmessage = function (msg) {\n' );
document.write( '				if (msg.data == \'reload\') window.location.reload();\n' );
document.write( '				else if (msg.data == \'refreshcss\') refreshCSS();\n' );
document.write( '			};\n' );
document.write( '			if (sessionStorage && !sessionStorage.getItem(\'IsThisFirstTime_Log_From_LiveServer\')) {\n' );
document.write( '				console.log(\'Live reload enabled.\');\n' );
document.write( '				sessionStorage.setItem(\'IsThisFirstTime_Log_From_LiveServer\', true);\n' );
document.write( '			}\n' );
document.write( '		})();\n' );
document.write( '	}\n' );
document.write( '	else {\n' );
document.write( '		console.error(\'Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.\');\n' );
document.write( '	}\n' );
document.write( '	// ]]>\n' );
document.write( '</script>\n' );
document.write( '\n' );
document.write( '\n' );
